# numpy 유용 함수들 정리
- 자세하게는 정리하지 않을 것


- `np.array` 배열에 값 추가하기 --> `np.append(arr, np.array([1,2]))`

In [ ]:
import numpy as np
n = np.array([1,2,3])
print(n)
n2 = np.append(n, np.array([1,2]))
print(n2)

[1 2 3]
[1 2 3 1 2]


- `np.zeros` 함수 --> 0 값이 채워진 배열 생성

In [ ]:
npz = np.zeros((2,3))
print(npz)

[[0. 0. 0.]
 [0. 0. 0.]]


- 각 차원을 축(axis) 라고 함
- 축의 개수를 랭크(rank) 라고 함  
  예를 들어 (3x4) 배열은 랭크가 2인 배열. 첫 번째 축의 길이는 3, 두 번째 축의 길이는 4
- 배열의 축 길이를 배열의 크기(shape) 라고 함. 위 행렬의 크기는 (3, 4)

- `arr.shape` : arr 배열의 크기(shape) 
- `arr.ndim`  : arr 배열의 rank 값
- `arr.size`  : arr 배열을 1차원으로 변경하였을 때의 length 

In [ ]:
arr = np.zeros((3, 4))
print(arr.shape)
print(arr.ndim)
print(arr.size)


(3, 4)
2
12


## N-차원 배열 만들기
- np.function의 차원에 (a, b, c) 형태로 입력하면 N-차원 배열로 변경됨
- <b>넘파이 배열의 타입은 ndarray !</b>

In [ ]:
type(np.zeros((3,4)))

numpy.ndarray

`np.ones` : 1로 채워진 넘파이 배열 생성

In [ ]:
np_o = np.ones((3,4))
print(np_o)

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


`np.full((dim), value)` : 지정된 값(value)으로 넘파이 배열 생성

In [ ]:
np.full((3,4), np.pi)

array([[3.14159265, 3.14159265, 3.14159265, 3.14159265],
       [3.14159265, 3.14159265, 3.14159265, 3.14159265],
       [3.14159265, 3.14159265, 3.14159265, 3.14159265]])

`np.empty` : 초기화 되지 않은  넘파이 배열 생성
메모리의 상태에 따라 다름




In [ ]:
np.empty((2,3,4))

`np.array` : 넘파이 배열 선언

In [ ]:
np.array([[1,2,3,4], [2,3,4,5]])

array([[1, 2, 3, 4],
       [2, 3, 4, 5]])

`np.arange(1, 10)` : 파이썬의 range와 비슷한 함수. 넘파이 배열을 반환 

In [ ]:
np.arange(1, 10)
np.arange(1.0, 5.5, 0.5)
# 세번째 인자는 간격을 나타내는데, 이 간격은 부동소수점일 경우 작은 오차에 따라서 값이 달라짐
print(np.arange(0, 5/3, 0.33333))
print(np.arange(0, 5/3, 0.33334))

[0.      0.33333 0.66666 0.99999 1.33332 1.66665]
[0.      0.33334 0.66668 1.00002 1.33336]


`np.linspace` : 위와 같은 이유로 `linspace` 함수를 사용하는 것이 좋음  
세 번째 인수는 range의 개수를 나타냄

In [ ]:
np.linspace(0, 5/3, 6)

array([0.        , 0.33333333, 0.66666667, 1.        , 1.33333333,
       1.66666667])

- `np.rand` : 0과 1사이의 난수 생성
- `np.randn` : 평균이 0이고 분산이 1인 정규 분포에서의 난수 생성

In [ ]:
print(np.random.rand(3,4))
print(np.random.randn(3,4))

[[0.72883749 0.44048462 0.9900596  0.35320919]
 [0.45184204 0.05066173 0.90935254 0.41818992]
 [0.22304906 0.23459254 0.02928947 0.60102282]]
[[ 0.30721632 -1.44608029  0.9153016   0.68114508]
 [-1.51147288 -0.03282755  0.87838202  0.00547636]
 [-0.47132269  0.30320932 -0.18523779  0.9096439 ]]


- `np.fromfunction(myfunction, (shape))` : fromfunction을 이용해서 함수를 초기화 할 수 있음  
- 다음 예제를 잘 이해해보자
- 중요한 점은 해당 원소가 여러번 호출되는 것이 아니라 딱 한번 호출되는 것 

In [ ]:
def myfunction(z,y,x):
  return x * y + z
np.fromfunction(myfunction, (3,2,10))

array([[[ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
        [ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9.]],

       [[ 1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.],
        [ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.]],

       [[ 2.,  2.,  2.,  2.,  2.,  2.,  2.,  2.,  2.,  2.],
        [ 2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11.]]])

## 배열 속 데이터
- 넘파이의 ndarray는 모든 원소가 동일한 타입을 가지고 있기 때문에 효율적
- `dtype` 속성으로 데이터 타입을 확인 가능 

In [ ]:
ad = np.array([1,2,2,3,5])
ad.dtype

c = np.arange(1.0, 10.0, 2)
print(c.dtype, c)

npf = np.array([1,2,3,4], dtype = 'float64')
print(npf)

float64 [1. 3. 5. 7. 9.]
[1. 2. 3. 4.]


`itemsize` 속성은 배열의 바이트 크기를 반환

In [ ]:
a = np.arange(1, 100)
a.itemsize

8

## 배열 크기 변경

`ndarray`의 `shape` 속성을 지정하면 크기 변경이 가능

In [ ]:
g = np.arange(24)
g.shape = (3, 8)
print(g)

[[ 0  1  2  3  4  5  6  7]
 [ 8  9 10 11 12 13 14 15]
 [16 17 18 19 20 21 22 23]]


`reshape` 함수는 넘파이 배열의 차원을 변경하여 해당 배열을 반환

In [ ]:
g = np.arange(24)
g2 = g.reshape(4, 6)

print("g:", g)
print("g2", g2)

g: [ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23]
g2 [[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]
 [12 13 14 15 16 17]
 [18 19 20 21 22 23]]


만약 위에서 선언한 `g2` 배열의 특정 원소를 변경하면 어떻게 될까요?    
중요한 것은 `g` 넘파이 배열도 같이 값이 변경된다는 것입니다

In [ ]:
g2[1, 2] = 999
print(g2)
print(g)

[[  0   1   2   3   4   5]
 [  6   7 999   9  10  11]
 [ 12  13  14  15  16  17]
 [ 18  19  20  21  22  23]]
[  0   1   2   3   4   5   6   7 999   9  10  11  12  13  14  15  16  17
  18  19  20  21  22  23]


- `g.ravel` 함수는 동일한 데이터를 가리키는 새로운 1차원 `ndarray` 를 반환

In [ ]:
g.ravel()

array([  0,   1,   2,   3,   4,   5,   6,   7, 999,   9,  10,  11,  12,
        13,  14,  15,  16,  17,  18,  19,  20,  21,  22,  23])

## 산술 연산자
- 일반적인 산술 연산자를 ndarray 타입에 적용할 수 있음
- 이 연산자는 원소별로 연산이 수행됨
- 배열의 크기는 같아야 함
- 여기서의 곱셈은 행렬 곱셈이 아니라 원소별 곱셈임을 조심하자

In [ ]:
a = np.array([14, 23, 29, 93])
b = np.array([1, 2,  3,  4])
print("a + b = ", a + b)
print("a * b = ", a * b)
print("a / b = ", a / b)
print("a // b = ", a // b)
print("a % b = ", a % b)
print("a ** b = ", a ** b)

a + b =  [15 25 32 97]
a * b =  [ 14  46  87 372]
a / b =  [14.         11.5         9.66666667 23.25      ]
a // b =  [14 11  9 23]
a % b =  [0 1 2 1]
a ** b =  [      14      529    24389 74805201]


## 브로드캐스팅
- 일반적으로 넘파이 배열은 동일한 크기의 길이를 예상하지만, 그렇지 않을 경우에는 브로드캐스팅 규칙을 적용  
- 규칙 1 : 배열의 rank가 맞지 않으면, 맞을 때까지 rank 앞에 1을 추가함
- 규칙 2 : 특정 차원이 1인 배열은 그 차원에서 크기가 가장 큰 배열의 크기에 맞춰 생성됨
- 규칙 3 : 규칙 1 & 2를 적용했을 때 배열의 크기가 맞아야 함

In [ ]:
# 규칙1
h = np.arange(1, 5).reshape(1, 1, 4)
h + np.array([1,2,3,4])

# 규칙2
k = np.arange(6).reshape(2, 3)
k + [[100], [200]]

array([[100, 101, 102],
       [203, 204, 205]])

In [ ]:
a = [1,2,3,4]
b = [4,3,2,1]
np.maximum(a, b)
np.minimum(a, b)


array([4, 3, 3, 4])

## 보통의 배열과 넘파이 배열과의 차이점
- ndarray 슬라이싱에 하나의 값을 할당하면, 하나의 값이 중복돼서 저장됨


In [ ]:
a = np.arange(1, 10)
a[2:5] = 999
a

array([  1,   2, 999, 999, 999,   6,   7,   8,   9])

- 또한 이런 식으로 ndarray 크기를 늘리거나 줄일 수 없습니다:

In [ ]:
try:
  a[2:5] = [1,2,3,3,4,5]
except ValueError as e:
  print(e)

cannot copy sequence with size 6 to array axis with dimension 3


- 원소 삭제도 안됨

In [ ]:
try:
  del a[2:5]
except ValueError as e:
  print(e)

cannot delete array elements


- 중요한 점은 ndarray의 슬라이싱 수행시 원본 객체가 같이 수정된다는 점
- 즉 ndarray는 같은 데이터 버퍼를 바라보면 view
- 데이터를 복사하려면 `copy()` 를 사용해야 함


## 다차원 배열
- 다음의 두 경우에는 미묘한 차이가 있는데, 첫 번째 것은 1D인 배열이, 두 번째 것은 2D인 배열이 return 됨

In [ ]:
b = np.arange(48).reshape(4, 12)
print(b[1, :])
print(b[1:2, :])

[12 13 14 15 16 17 18 19 20 21 22 23]
[[12 13 14 15 16 17 18 19 20 21 22 23]]


## 팬시 인덱싱(Fancy indexing)
- 관심 대상의 리스트를 지정할 수도 있음


In [ ]:
b[(0, 2), 2:4]
b[:, (-1, 2, -1)]

array([[11,  2, 11],
       [23, 14, 23],
       [35, 26, 35],
       [47, 38, 47]])

- 여러 개의 인덱스 리스트를 지정하면, 인덱스에 맞는 값이 포함된 1D ndarray를 반환함  

In [ ]:
b[(-1, 2, -1, 2), (5, 9, 5, 9)]

array([41, 33, 41, 33])

## 고차원
- 고차원에서의 슬라이싱은 마찬가지
- 만약 특정 인덱스를 지정하지 않으면 모든 값이 선택됨 --> [:] 과 동일
- 생략 부호(...)를 쓰면 지정하지 않는 축의 원소를 반환


In [ ]:
a = np.arange(24).reshape(3,4,2)
print(a)
print("=========")
print(a[1, ...])
print("=========")
print(a[..., 1])

[[[ 0  1]
  [ 2  3]
  [ 4  5]
  [ 6  7]]

 [[ 8  9]
  [10 11]
  [12 13]
  [14 15]]

 [[16 17]
  [18 19]
  [20 21]
  [22 23]]]
[[ 8  9]
 [10 11]
 [12 13]
 [14 15]]
[[ 1  3  5  7]
 [ 9 11 13 15]
 [17 19 21 23]]


## 불리언 인덱싱
- boolean 값을 가진 배열을 이용해 ndarray 슬라이싱 가능
- 여러 축에 걸쳐서는 `ix_` 함수를 사용
- 반복은 파이썬에서 사용하는 기본적인 반복 사용 가능

In [ ]:
a = np.arange(24).reshape(4, 6)
a_boolean = np.array([True, False, True, False])
b_boolean = np.array([True, False] * 3)

print(a.shape)
print(a_boolean)
print(b_boolean)

print(a[a_boolean, :])
print(a[:, b_boolean])
print(a[np.ix_(a_boolean, b_boolean)])

(4, 6)
[ True False  True False]
[ True False  True False  True False]
[[ 0  1  2  3  4  5]
 [12 13 14 15 16 17]]
[[ 0  2  4]
 [ 6  8 10]
 [12 14 16]
 [18 20 22]]
[[ 0  2  4]
 [12 14 16]]


## 배열 쌓기
- `np.vstack` : 행결합
- `np.hstack` : 열결합
- `concetenate` : 지정한 축으로 배열 쌓기
- `stack` : 새로운 축을 따라 쌓음. 쌓으려고 하는 배열의 차원이 같아야 함 

In [ ]:
a = np.arange(24).reshape(4, 6)
b = np.arange(24).reshape(4, 6)

print(np.vstack((a, b)))
print(np.hstack((a, b)))
print(np.concatenate((a,b), axis=0))
print(np.stack((a,b)))

[[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]
 [12 13 14 15 16 17]
 [18 19 20 21 22 23]
 [ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]
 [12 13 14 15 16 17]
 [18 19 20 21 22 23]]
[[ 0  1  2  3  4  5  0  1  2  3  4  5]
 [ 6  7  8  9 10 11  6  7  8  9 10 11]
 [12 13 14 15 16 17 12 13 14 15 16 17]
 [18 19 20 21 22 23 18 19 20 21 22 23]]
[[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]
 [12 13 14 15 16 17]
 [18 19 20 21 22 23]
 [ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]
 [12 13 14 15 16 17]
 [18 19 20 21 22 23]]
[[[ 0  1  2  3  4  5]
  [ 6  7  8  9 10 11]
  [12 13 14 15 16 17]
  [18 19 20 21 22 23]]

 [[ 0  1  2  3  4  5]
  [ 6  7  8  9 10 11]
  [12 13 14 15 16 17]
  [18 19 20 21 22 23]]]


## 배열 분할
- 분할은 쌓기의 반대임
- `vsplit` : 수직으로 배열을 분할함
- `hsplit` : 수평으로 배열을 분할함

In [ ]:
np.vsplit(a, 2)
np.hsplit(a, 3)

[array([[ 0,  1],
        [ 6,  7],
        [12, 13],
        [18, 19]]), array([[ 2,  3],
        [ 8,  9],
        [14, 15],
        [20, 21]]), array([[ 4,  5],
        [10, 11],
        [16, 17],
        [22, 23]])]

## 배열 전치
- `transpose` --> 축을 뒤바꾸어 ndarray의 데이터에 대한 새로운 뷰를 만듬
- 예를 들어 3D 배열을 만들어보자

In [ ]:
t = np.arange(24).reshape(4, 2, 3)
t

array([[[ 0,  1,  2],
        [ 3,  4,  5]],

       [[ 6,  7,  8],
        [ 9, 10, 11]],

       [[12, 13, 14],
        [15, 16, 17]],

       [[18, 19, 20],
        [21, 22, 23]]])

In [ ]:
t2 = t.transpose(1, 2, 0)
print(t.shape)
print(t2.shape)

(4, 2, 3)
(2, 3, 4)


`swapaxes` --> 두 축을 바꾸는 함수 제공


In [ ]:
t.swapaxes(0, 1) # t.transpose(1, 0, 2)와 동일

array([[[ 0,  1,  2],
        [ 6,  7,  8],
        [12, 13, 14],
        [18, 19, 20]],

       [[ 3,  4,  5],
        [ 9, 10, 11],
        [15, 16, 17],
        [21, 22, 23]]])

- 행렬 전치
  - `T` --> rank가 2보다 클때 행렬 전치 수행  
  - rank가 1일 때는 아무런 영향을 미치지 않음
- 행렬 점곱
  - `dot` --> 행렬 점곱 수행
- 역행렬과 유사 역행렬
  - `numpy.linalg` 모듈 안에는 많은 선형 대수 함수들이 들어가 있음
  - `inv`  --> 정방 행렬의 역함수 계산
  - `pinv` --> 유사 역행렬 계산
  - `eye`  --> NxN의 단위행렬 생성
  - `qr`   --> 행렬을 QR 분해함
  - `det`  --> 행렬식(determinant) 계산
  - `eig`  --> 고윳값(eigenvalue), 고유벡터(eigenVector) 계산
  - `svd`  --> 특이값 분해
  - `np.diag` --> 원소의 대각원소
  - `np.trace` --> 원소의 대각합
  - `linalg.solve` --> 선형 방정식 계산

## 벡터화
- 한 번에 하나씩 개별 원소를 계산하는 것 보다 배열 연산을 사용하면 훨씬 효율적인 코드를 작성할 수 있음
- 이를 사용하여 넘파이의 최적화된 성능 활용 가능
- `np.meshgrid` --> 좌표 벡터 생성 가능

In [ ]:
x_coords = np.arange(0, 1024) # [0, 1, 2, ..., 1023]
y_coords = np.arange(0, 768) # [0, 1, 2, ..., 767]
X, Y = np.meshgrid(x_coords, y_coords)
print(X)
print(Y)
data = np.sin(X*Y/40.5)