In [91]:
# 다항차수 변환, 교호작용 변수 생성
# sklearn.preprocessing.PolynomialFeatures 을 활용한 다항차수 변환 및 교호작용 생성
# 다항 차수를 생성해서 비선형 관계를 표현하거나, 변수간 곱을 사용해서 교호작용 효과를 나타낼 수 있는 변수를 만듬

In [92]:
import numpy as np
import pandas as pd
from sklearn.preprocessing import PolynomialFeatures
X = np.arange(6).reshape(3, 2)

poly = PolynomialFeatures(degree = 2)
poly.fit_transform(X)

array([[ 1.,  0.,  1.,  0.,  0.,  1.],
       [ 1.,  2.,  3.,  4.,  6.,  9.],
       [ 1.,  4.,  5., 16., 20., 25.]])

In [93]:
X

array([[0, 1],
       [2, 3],
       [4, 5]])

In [95]:
p = pd.DataFrame({
    'A':['a', 'b', 'c'],
    'B':[1,2,3]
})

In [110]:
import scipy.stats as ss
from sklearn.preprocessing import StandardScaler
np.random.seed(42)
data = np.random.randint(30, size = (6, 5))
data

array([[ 6, 19, 28, 14, 10],
       [ 7, 28, 20,  6, 25],
       [18, 22, 10, 10, 23],
       [20,  3,  7, 23,  2],
       [21, 20,  1, 23, 11],
       [29,  5,  1, 27, 20]])

In [111]:
ss.zscore(data)

array([[-1.34227633,  0.31199226,  1.70211289, -0.41412128, -0.63370969],
       [-1.2183739 ,  1.30302651,  0.89318795, -1.46032242,  1.20609263],
       [ 0.14455284,  0.64233701, -0.11796822, -0.93722185,  0.96078565],
       [ 0.3923577 , -1.44984639, -0.42131507,  0.762855  , -1.61493758],
       [ 0.51626013,  0.42210718, -1.02800878,  0.762855  , -0.5110562 ],
       [ 1.50747958, -1.22961656, -1.02800878,  1.28595556,  0.59282519]])

In [112]:
StandardScaler().fit_transform(data)

array([[-1.34227633,  0.31199226,  1.70211289, -0.41412128, -0.63370969],
       [-1.2183739 ,  1.30302651,  0.89318795, -1.46032242,  1.20609263],
       [ 0.14455284,  0.64233701, -0.11796822, -0.93722185,  0.96078565],
       [ 0.3923577 , -1.44984639, -0.42131507,  0.762855  , -1.61493758],
       [ 0.51626013,  0.42210718, -1.02800878,  0.762855  , -0.5110562 ],
       [ 1.50747958, -1.22961656, -1.02800878,  1.28595556,  0.59282519]])